............................................................................................................file.at.apply........................const fs = require('fs');
const path = require('path');
const file = path.join(__dirname, 'src', 'app', 'components', 'ProfileSettings.tsx');

const lines = [];
const p = (s) => lines.push(s);

p(`import { useState, useEffect, useRef } from 'react';`);
p(`import { useNavigate } from 'react-router';`);
p(`import { User, Bell, Globe, Shield, Settings, Camera, Mail, Phone, MapPin, Moon, Sun, Lock, Smartphone, Monitor, AlertTriangle, LogOut, Trash2, Check, ChevronDown, ChevronRight, Loader2, Eye, EyeOff } from 'lucide-react';`);
p(`import { api, UserResponse, FarmResponse } from '../api/client';`);
p(`import { useAuth } from '../auth/AuthContext';`);
p(``);
p(`export default function ProfileSettings() {`);
p(`  const navigate = useNavigate();`);
p(`  const { logout } = useAuth();`);
p(`  const fileInputRef = useRef<HTMLInputElement>(null);`);
p(`  const [activeTab, setActiveTab] = useState('profile');`);
p(`  const [loading, setLoading] = useState(false);`);
p(`  const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null);`);
p(`  const [user, setUser] = useState<UserResponse | null>(null);`);
p(`  const [avatarPreview, setAvatarPreview] = useState<string | null>(() => localStorage.getItem('avatar_data'));`);
p(`  const [profileForm, setProfileForm] = useState({ full_name: '', phone: '', email: '', location: '', bio: '' });`);
p(`  const [passwordForm, setPasswordForm] = useState({ current: '', new: '', confirm: '' });`);
p(`  const [showPw, setShowPw] = useState({ current: false, new: false, confirm: false });`);
p(`  const [darkMode, setDarkMode] = useState(() => localStorage.getItem('theme') === 'dark');`);
p(`  const [language, setLanguage] = useState(() => localStorage.getItem('language') || 'en-US');`);
p(`  const [timezone, setTimezone] = useState(() => localStorage.getItem('timezone') || 'CT');`);
p(`  const [units, setUnits] = useState(() => localStorage.getItem('units') || 'imperial');`);
p(`  const [notifications, setNotifications] = useState<Record<string, boolean>>(() => {`);
p(`    const saved = localStorage.getItem('notifications');`);
p(`    return saved ? JSON.parse(saved) : { email: true, push: true, sms: false, weather: true, yield: true, disease: true, market: false };`);
p(`  });`);
p(`  const [farms, setFarms] = useState<FarmResponse[]>([]);`);
p(`  const [farmPrefs, setFarmPrefs] = useState({`);
p(`    default_farm: localStorage.getItem('default_farm') || '',`);
p(`    primary_crop: localStorage.getItem('primary_crop') || 'wheat',`);
p(`    farming_type: localStorage.getItem('farming_type') || 'organic',`);
p(`  });`);
p(`  const [twoFAEnabled, setTwoFAEnabled] = useState(() => localStorage.getItem('2fa_enabled') === 'true');`);
p(``);
p(`  useEffect(() => { loadUserData(); loadFarms(); }, []);`);
p(`  useEffect(() => {`);
p(`    document.documentElement.classList.toggle('dark', darkMode);`);
p(`    localStorage.setItem('theme', darkMode ? 'dark' : 'light');`);
p(`  }, [darkMode]);`);
p(``);
p(`  const showMessage = (type: 'success' | 'error', text: string) => {`);
p(`    setMessage({ type, text });`);
p(`    setTimeout(() => setMessage(null), 5000);`);
p(`  };`);
p(``);
p(`  const loadUserData = async () => {`);
p(`    try {`);
p(`      const u = await api.me();`);
p(`      setUser(u);`);
p(`      setProfileForm({`);
p(`        full_name: u.full_name || '',`);
p(`        phone: u.phone || '',`);
p(`        email: u.email || '',`);
p(`        location: localStorage.getItem('user_location') || '',`);
p(`        bio: localStorage.getItem('user_bio') || '',`);
p(`      });`);
p(`    } catch { showMessage('error', 'Failed to load user data'); }`);
p(`  };`);
p(``);
p(`  const loadFarms = async () => {`);
p(`    try { const data = await api.getFarms(); setFarms(data); } catch { /* optional */ }`);
p(`  };`);
p(``);
p(`  const handlePhotoChange = (e: React.ChangeEvent<HTMLInputElement>) => {`);
p(`    const file = e.target.files?.[0];`);
p(`    if (!file) return;`);
p(`    if (file.size > 2 * 1024 * 1024) { showMessage('error', 'Image must be under 2 MB'); return; }`);
p(`    const reader = new FileReader();`);
p(`    reader.onload = () => {`);
p(`      const d = reader.result as string;`);
p(`      setAvatarPreview(d);`);
p(`      localStorage.setItem('avatar_data', d);`);
p(`      showMessage('success', 'Profile photo updated');`);
p(`    };`);
p(`    reader.readAsDataURL(file);`);
p(`  };`);
p(``);
p(`  const handleRemovePhoto = () => {`);
p(`    setAvatarPreview(null);`);
p(`    localStorage.removeItem('avatar_data');`);
p(`    if (fileInputRef.current) fileInputRef.current.value = '';`);
p(`    showMessage('success', 'Photo removed');`);
p(`  };`);
p(``);
p(`  const handleProfileUpdate = async (e: React.FormEvent) => {`);
p(`    e.preventDefault();`);
p(`    setLoading(true);`);
p(`    try {`);
p(`      const updated = await api.updateProfile({ full_name: profileForm.full_name, phone: profileForm.phone || undefined });`);
p(`      setUser(updated);`);
p(`      localStorage.setItem('user_location', profileForm.location);`);
p(`      localStorage.setItem('user_bio', profileForm.bio);`);
p(`      showMessage('success', 'Profile updated successfully');`);
p(`    } catch (err: any) { showMessage('error', err.message || 'Failed to update profile'); }`);
p(`    finally { setLoading(false); }`);
p(`  };`);
p(``);
p(`  const handlePasswordChange = async (e: React.FormEvent) => {`);
p(`    e.preventDefault();`);
p(`    if (passwordForm.new !== passwordForm.confirm) { showMessage('error', 'Passwords do not match'); return; }`);
p(`    if (!/(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[!@#$%^&*]).{8,}/.test(passwordForm.new)) {`);
p(`      showMessage('error', 'Password needs 8+ chars, uppercase, lowercase, digit and special char');`);
p(`      return;`);
p(`    }`);
p(`    setLoading(true);`);
p(`    try {`);
p(`      await api.changePassword(passwordForm.current, passwordForm.new);`);
p(`      setPasswordForm({ current: '', new: '', confirm: '' });`);
p(`      showMessage('success', 'Password changed successfully');`);
p(`    } catch (err: any) { showMessage('error', err.message || 'Failed to change password'); }`);
p(`    finally { setLoading(false); }`);
p(`  };`);
p(``);
p(`  const handleNotificationToggle = (key: string) => {`);
p(`    const u = { ...notifications, [key]: !notifications[key] };`);
p(`    setNotifications(u);`);
p(`    localStorage.setItem('notifications', JSON.stringify(u));`);
p(`    showMessage('success', 'Saved');`);
p(`  };`);
p(``);
p(`  const handlePreferencesSave = () => {`);
p(`    localStorage.setItem('language', language);`);
p(`    localStorage.setItem('timezone', timezone);`);
p(`    localStorage.setItem('units', units);`);
p(`    showMessage('success', 'Preferences saved');`);
p(`  };`);
p(``);
p(`  const handleFarmPrefsSave = () => {`);
p(`    localStorage.setItem('default_farm', farmPrefs.default_farm);`);
p(`    localStorage.setItem('primary_crop', farmPrefs.primary_crop);`);
p(`    localStorage.setItem('farming_type', farmPrefs.farming_type);`);
p(`    showMessage('success', 'Farm settings saved');`);
p(`  };`);
p(``);
p(`  const handle2FAToggle = () => {`);
p(`    const n = !twoFAEnabled;`);
p(`    setTwoFAEnabled(n);`);
p(`    localStorage.setItem('2fa_enabled', String(n));`);
p(`    showMessage('success', n ? '2FA enabled' : '2FA disabled');`);
p(`  };`);
p(``);
p(`  const handleLogout = async () => { await logout(); navigate('/login'); };`);
p(`  const handleDeleteAccount = () => {`);
p(`    if (window.confirm('Delete your account? This cannot be undone.')) {`);
p(`      showMessage('error', 'Contact support to delete your account.');`);
p(`    }`);
p(`  };`);
p(``);
p(`  const initials = user?.full_name?.split(' ').map(n => n[0]).join('').toUpperCase().slice(0, 2) || 'U';`);
p(`  const tabs = [`);
p(`    { id: 'profile', label: 'Profile', icon: User },`);
p(`    { id: 'notifications', label: 'Notifications', icon: Bell },`);
p(`    { id: 'preferences', label: 'Preferences', icon: Globe },`);
p(`    { id: 'security', label: 'Security', icon: Shield },`);
p(`    { id: 'farm', label: 'Farm Settings', icon: Settings },`);
p(`  ];`);
p(``);
p(`  const Toggle = ({ on, onToggle }: { on: boolean; onToggle: () => void }) => (`);
p(`    <button type="button" onClick={onToggle}`);
p(`      className={\`relative w-14 h-7 rounded-full transition-colors \${on ? 'bg-gradient-to-r from-emerald-500 to-teal-600' : 'bg-gray-300'}\`}>`);
p(`      <span className={\`absolute top-1 left-1 w-5 h-5 bg-white rounded-full transition-transform \${on ? 'translate-x-7' : 'translate-x-0'}\`} />`);
p(`    </button>`);
p(`  );`);

p(``);
p(`  return (`);
p(`    <div className="space-y-6">`);
p(`      {message && (`);
p(`        <div className={\`backdrop-blur-lg border rounded-2xl px-6 py-4 \${message.type === 'success' ? 'bg-emerald-50/80 border-emerald-200 text-emerald-800' : 'bg-red-50/80 border-red-200 text-red-800'}\`}>`);
p(`          <p className="font-medium">{message.text}</p>`);
p(`        </div>`);
p(`      )}`);
p(``);
p(`      {/* Header */}`);
p(`      <div className="backdrop-blur-lg bg-white/80 border border-emerald-100 rounded-2xl px-4 sm:px-6 py-4">`);
p(`        <div className="flex items-center justify-between gap-4">`);
p(`          <div>`);
p(`            <h1 className="text-xl font-bold text-gray-800">Settings</h1>`);
p(`            <p className="text-sm text-gray-600 hidden sm:block">Manage your account and preferences</p>`);
p(`          </div>`);
p(`          <div className="flex items-center gap-3 px-4 py-2 bg-white/60 rounded-lg border border-emerald-100">`);
p(`            <div className="w-8 h-8 rounded-full overflow-hidden bg-gradient-to-br from-emerald-600 to-teal-600 flex items-center justify-center text-white text-xs font-bold">`);
p(`              {avatarPreview ? <img src={avatarPreview} alt="avatar" className="w-full h-full object-cover" /> : initials}`);
p(`            </div>`);
p(`            <div className="hidden sm:block">`);
p(`              <div className="text-sm font-medium text-gray-800">{user?.full_name || 'Loading...'}</div>`);
p(`              <div className="text-xs text-gray-600 capitalize">{user?.role || 'User'}</div>`);
p(`            </div>`);
p(`            <ChevronDown className="w-4 h-4 text-gray-600 hidden sm:block" />`);
p(`          </div>`);
p(`        </div>`);
p(`      </div>`);
p(``);
p(`      <div className="p-4 sm:p-6 lg:p-8">`);
p(`        {/* Tab nav */}`);
p(`        <div className="mb-6 overflow-x-auto">`);
p(`          <div className="flex gap-2 min-w-max pb-2">`);
p(`            {tabs.map(tab => (`);
p(`              <button key={tab.id} onClick={() => setActiveTab(tab.id)}`);
p(`                className={\`flex items-center gap-2 px-4 py-3 rounded-xl transition-all whitespace-nowrap \${activeTab === tab.id ? 'bg-gradient-to-r from-emerald-500 to-teal-600 text-white shadow-lg' : 'bg-white/60 text-gray-700 hover:bg-white border border-emerald-100'}\`}>`);
p(`                <tab.icon className="w-5 h-5" />`);
p(`                <span className="font-medium">{tab.label}</span>`);
p(`              </button>`);
p(`            ))}`);
p(`          </div>`);
p(`        </div>`);
p(``);
p(`        <div className="max-w-4xl mx-auto">`);
p(``);
p(`          {/* PROFILE */}`);
p(`          {activeTab === 'profile' && (`);
p(`            <div className="space-y-6">`);
p(`              <div>`);
p(`                <h2 className="text-2xl font-bold text-gray-800 mb-1">Profile Information</h2>`);
p(`                <p className="text-gray-600">Update your personal details and profile picture</p>`);
p(`              </div>`);
p(`              <div className="backdrop-blur-lg bg-white/60 border border-white/50 rounded-2xl p-6 shadow-xl">`);
p(`                <div className="flex items-center gap-6">`);
p(`                  <div className="relative">`);
p(`                    <div className="w-24 h-24 rounded-full overflow-hidden bg-gradient-to-br from-emerald-500 to-teal-600 flex items-center justify-center text-white text-3xl font-bold">`);
p(`                      {avatarPreview ? <img src={avatarPreview} alt="avatar" className="w-full h-full object-cover" /> : initials}`);
p(`                    </div>`);
p(`                    <button type="button" onClick={() => fileInputRef.current?.click()}`);
p(`                      className="absolute bottom-0 right-0 w-8 h-8 bg-white rounded-full shadow-lg flex items-center justify-center border-2 border-emerald-100 hover:bg-emerald-50 transition-colors">`);
p(`                      <Camera className="w-4 h-4 text-emerald-600" />`);
p(`                    </button>`);
p(`                    <input ref={fileInputRef} type="file" accept="image/*" className="hidden" onChange={handlePhotoChange} />`);
p(`                  </div>`);
p(`                  <div>`);
p(`                    <h3 className="font-bold text-gray-800 text-lg">{user?.full_name || 'User'}</h3>`);
p(`                    <p className="text-gray-600 text-sm">{user?.email || ''}</p>`);
p(`                    <div className="flex gap-3 mt-2">`);
p(`                      <button type="button" onClick={() => fileInputRef.current?.click()} className="text-emerald-600 text-sm font-medium hover:text-emerald-700">Upload photo</button>`);
p(`                      {avatarPreview && <button type="button" onClick={handleRemovePhoto} className="text-red-500 text-sm font-medium hover:text-red-700">Remove</button>}`);
p(`                    </div>`);
p(`                    <p className="text-xs text-gray-400 mt-1">JPG, PNG or GIF · max 2 MB</p>`);
p(`                  </div>`);
p(`                </div>`);
p(`              </div>`);
p(`              <form onSubmit={handleProfileUpdate}>`);
p(`                <div className="backdrop-blur-lg bg-white/60 border border-white/50 rounded-2xl p-6 shadow-xl">`);
p(`                  <h3 className="font-bold text-gray-800 mb-4">Personal Information</h3>`);
p(`                  <div className="grid grid-cols-2 gap-4">`);
p(`                    <div className="col-span-2">`);
p(`                      <label className="block text-sm font-medium text-gray-700 mb-2">Full Name</label>`);
p(`                      <input type="text" value={profileForm.full_name} required`);
p(`                        onChange={e => setProfileForm(p => ({ ...p, full_name: e.target.value }))}`);
p(`                        className="w-full px-4 py-3 rounded-xl border border-emerald-100 bg-white/50 focus:outline-none focus:ring-2 focus:ring-emerald-500/50 focus:border-emerald-500" />`);
p(`                    </div>`);
p(`                    <div className="col-span-2 sm:col-span-1">`);
p(`                      <label className="block text-sm font-medium text-gray-700 mb-2">Email <span className="text-gray-400 text-xs">(read-only)</span></label>`);
p(`                      <div className="relative">`);
p(`                        <Mail className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />`);
p(`                        <input type="email" value={profileForm.email} disabled`);
p(`                          className="w-full pl-11 pr-4 py-3 rounded-xl border border-emerald-100 bg-gray-100 text-gray-500 cursor-not-allowed" />`);
p(`                      </div>`);
p(`                    </div>`);
p(`                    <div className="col-span-2 sm:col-span-1">`);
p(`                      <label className="block text-sm font-medium text-gray-700 mb-2">Phone</label>`);
p(`                      <div className="relative">`);
p(`                        <Phone className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />`);
p(`                        <input type="tel" value={profileForm.phone} placeholder="+1 (555) 000-0000"`);
p(`                          onChange={e => setProfileForm(p => ({ ...p, phone: e.target.value }))}`);
p(`                          className="w-full pl-11 pr-4 py-3 rounded-xl border border-emerald-100 bg-white/50 focus:outline-none focus:ring-2 focus:ring-emerald-500/50 focus:border-emerald-500" />`);
p(`                      </div>`);
p(`                    </div>`);
p(`                    <div className="col-span-2">`);
p(`                      <label className="block text-sm font-medium text-gray-700 mb-2">Location</label>`);
p(`                      <div className="relative">`);
p(`                        <MapPin className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />`);
p(`                        <input type="text" value={profileForm.location} placeholder="City, Country"`);
p(`                          onChange={e => setProfileForm(p => ({ ...p, location: e.target.value }))}`);
p(`                          className="w-full pl-11 pr-4 py-3 rounded-xl border border-emerald-100 bg-white/50 focus:outline-none focus:ring-2 focus:ring-emerald-500/50 focus:border-emerald-500" />`);
p(`                      </div>`);
p(`                    </div>`);
p(`                    <div className="col-span-2">`);
p(`                      <label className="block text-sm font-medium text-gray-700 mb-2">Bio</label>`);
p(`                      <textarea rows={3} value={profileForm.bio} placeholder="Tell us about yourself..."`);
p(`                        onChange={e => setProfileForm(p => ({ ...p, bio: e.target.value }))}`);
p(`                        className="w-full px-4 py-3 rounded-xl border border-emerald-100 bg-white/50 focus:outline-none focus:ring-2 focus:ring-emerald-500/50 focus:border-emerald-500 resize-none" />`);
p(`                    </div>`);
p(`                  </div>`);
p(`                  <button type="submit" disabled={loading}`);
p(`                    className="mt-6 px-6 py-3 bg-gradient-to-r from-emerald-500 to-teal-600 text-white rounded-xl font-medium hover:shadow-lg hover:shadow-emerald-500/30 transition-all disabled:opacity-50 flex items-center gap-2">`);
p(`                    {loading && <Loader2 className="w-4 h-4 animate-spin" />}Save Changes`);
p(`                  </button>`);
p(`                </div>`);
p(`              </form>`);
p(`            </div>`);
p(`          )}`);

p(``);
p(`          {/* NOTIFICATIONS */}`);
p(`          {activeTab === 'notifications' && (`);
p(`            <div className="space-y-6">`);
p(`              <div><h2 className="text-2xl font-bold text-gray-800 mb-1">Notification Preferences</h2><p className="text-gray-600">Manage how you receive updates and alerts</p></div>`);
p(`              <div className="backdrop-blur-lg bg-white/60 border border-white/50 rounded-2xl p-6 shadow-xl">`);
p(`                <h3 className="font-bold text-gray-800 mb-4">Channels</h3>`);
p(`                <div className="space-y-3">`);
p(`                  {[`);
p(`                    { id: 'email', label: 'Email Notifications', desc: 'Receive notifications via email' },`);
p(`                    { id: 'push', label: 'Push Notifications', desc: 'Get instant alerts on your device' },`);
p(`                    { id: 'sms', label: 'SMS Notifications', desc: 'Text messages for critical alerts' },`);
p(`                  ].map(ch => (`);
p(`                    <div key={ch.id} className="flex items-center justify-between p-4 rounded-xl bg-white/50 border border-emerald-100">`);
p(`                      <div><p className="font-medium text-gray-800">{ch.label}</p><p className="text-sm text-gray-600">{ch.desc}</p></div>`);
p(`                      <Toggle on={notifications[ch.id]} onToggle={() => handleNotificationToggle(ch.id)} />`);
p(`                    </div>`);
p(`                  ))}`);
p(`                </div>`);
p(`              </div>`);
p(`              <div className="backdrop-blur-lg bg-white/60 border border-white/50 rounded-2xl p-6 shadow-xl">`);
p(`                <h3 className="font-bold text-gray-800 mb-4">Alert Types</h3>`);
p(`                <div className="space-y-3">`);
p(`                  {[`);
p(`                    { id: 'weather', label: 'Weather Alerts', desc: 'Severe weather and forecast updates' },`);
p(`                    { id: 'yield', label: 'Yield Predictions', desc: 'AI-powered crop yield forecasts' },`);
p(`                    { id: 'disease', label: 'Disease Detection', desc: 'Crop health and disease warnings' },`);
p(`                    { id: 'market', label: 'Market Updates', desc: 'Price changes and market trends' },`);
p(`                  ].map(al => (`);
p(`                    <div key={al.id} className="flex items-center justify-between p-4 rounded-xl bg-white/50 border border-emerald-100">`);
p(`                      <div><p className="font-medium text-gray-800">{al.label}</p><p className="text-sm text-gray-600">{al.desc}</p></div>`);
p(`                      <Toggle on={notifications[al.id]} onToggle={() => handleNotificationToggle(al.id)} />`);
p(`                    </div>`);
p(`                  ))}`);
p(`                </div>`);
p(`              </div>`);
p(`            </div>`);
p(`          )}`);
p(``);
p(`          {/* PREFERENCES */}`);
p(`          {activeTab === 'preferences' && (`);
p(`            <div className="space-y-6">`);
p(`              <div><h2 className="text-2xl font-bold text-gray-800 mb-1">Preferences</h2><p className="text-gray-600">Customize your experience</p></div>`);
p(`              <div className="backdrop-blur-lg bg-white/60 border border-white/50 rounded-2xl p-6 shadow-xl">`);
p(`                <h3 className="font-bold text-gray-800 mb-4">Appearance</h3>`);
p(`                <div className="grid grid-cols-2 gap-4">`);
p(`                  <button type="button" onClick={() => setDarkMode(false)}`);
p(`                    className={\`p-6 rounded-xl border-2 transition-all \${!darkMode ? 'border-emerald-500 bg-emerald-50/50' : 'border-gray-200 bg-white/50 hover:border-emerald-200'}\`}>`);
p(`                    <div className="flex flex-col items-center gap-3">`);
p(`                      <div className="w-12 h-12 rounded-full bg-gradient-to-br from-amber-400 to-orange-500 flex items-center justify-center"><Sun className="w-6 h-6 text-white" /></div>`);
p(`                      <div className="text-center"><p className="font-medium text-gray-800">Light Mode</p><p className="text-sm text-gray-600">Bright and clean</p></div>`);
p(`                      {!darkMode && <div className="w-6 h-6 rounded-full bg-emerald-500 flex items-center justify-center"><Check className="w-4 h-4 text-white" /></div>}`);
p(`                    </div>`);
p(`                  </button>`);
p(`                  <button type="button" onClick={() => setDarkMode(true)}`);
p(`                    className={\`p-6 rounded-xl border-2 transition-all \${darkMode ? 'border-emerald-500 bg-emerald-50/50' : 'border-gray-200 bg-white/50 hover:border-emerald-200'}\`}>`);
p(`                    <div className="flex flex-col items-center gap-3">`);
p(`                      <div className="w-12 h-12 rounded-full bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center"><Moon className="w-6 h-6 text-white" /></div>`);
p(`                      <div className="text-center"><p className="font-medium text-gray-800">Dark Mode</p><p className="text-sm text-gray-600">Easy on the eyes</p></div>`);
p(`                      {darkMode && <div className="w-6 h-6 rounded-full bg-emerald-500 flex items-center justify-center"><Check className="w-4 h-4 text-white" /></div>}`);
p(`                    </div>`);
p(`                  </button>`);
p(`                </div>`);
p(`              </div>`);
p(`              <div className="backdrop-blur-lg bg-white/60 border border-white/50 rounded-2xl p-6 shadow-xl">`);
p(`                <h3 className="font-bold text-gray-800 mb-4">Language & Region</h3>`);
p(`                <div className="space-y-4">`);
p(`                  <div>`);
p(`                    <label className="block text-sm font-medium text-gray-700 mb-2">Language</label>`);
p(`                    <select value={language} onChange={e => setLanguage(e.target.value)} className="w-full px-4 py-3 rounded-xl border border-emerald-100 bg-white/50 focus:outline-none focus:ring-2 focus:ring-emerald-500/50">`);
p(`                      <option value="en-US">English (US)</option><option value="es">Spanish</option><option value="fr">French</option><option value="de">German</option>`);
p(`                    </select>`);
p(`                  </div>`);
p(`                  <div>`);
p(`                    <label className="block text-sm font-medium text-gray-700 mb-2">Timezone</label>`);
p(`                    <select value={timezone} onChange={e => setTimezone(e.target.value)} className="w-full px-4 py-3 rounded-xl border border-emerald-100 bg-white/50 focus:outline-none focus:ring-2 focus:ring-emerald-500/50">`);
p(`                      <option value="CT">Central Time (CT)</option><option value="ET">Eastern Time (ET)</option><option value="PT">Pacific Time (PT)</option><option value="MT">Mountain Time (MT)</option>`);
p(`                    </select>`);
p(`                  </div>`);
p(`                  <div>`);
p(`                    <label className="block text-sm font-medium text-gray-700 mb-2">Measurement Units</label>`);
p(`                    <select value={units} onChange={e => setUnits(e.target.value)} className="w-full px-4 py-3 rounded-xl border border-emerald-100 bg-white/50 focus:outline-none focus:ring-2 focus:ring-emerald-500/50">`);
p(`                      <option value="imperial">Imperial (acres, lbs)</option><option value="metric">Metric (hectares, kg)</option>`);
p(`                    </select>`);
p(`                  </div>`);
p(`                </div>`);
p(`                <button type="button" onClick={handlePreferencesSave} className="mt-6 px-6 py-3 bg-gradient-to-r from-emerald-500 to-teal-600 text-white rounded-xl font-medium hover:shadow-lg hover:shadow-emerald-500/30 transition-all">Save Preferences</button>`);
p(`              </div>`);
p(`            </div>`);
p(`          )}`);

p(``);
p(`          {/* SECURITY */}`);
p(`          {activeTab === 'security' && (`);
p(`            <div className="space-y-6">`);
p(`              <div><h2 className="text-2xl font-bold text-gray-800 mb-1">Security Settings</h2><p className="text-gray-600">Manage your account security</p></div>`);
p(`              <form onSubmit={handlePasswordChange}>`);
p(`                <div className="backdrop-blur-lg bg-white/60 border border-white/50 rounded-2xl p-6 shadow-xl">`);
p(`                  <h3 className="font-bold text-gray-800 mb-1">Change Password</h3>`);
p(`                  <p className="text-sm text-gray-500 mb-4">8+ chars with uppercase, lowercase, digit and special character.</p>`);
p(`                  <div className="space-y-4">`);
p(`                    {(['current', 'new', 'confirm'] as const).map(field => (`);
p(`                      <div key={field}>`);
p(`                        <label className="block text-sm font-medium text-gray-700 mb-2">`);
p(`                          {field === 'confirm' ? 'Confirm New Password' : field === 'new' ? 'New Password' : 'Current Password'}`);
p(`                        </label>`);
p(`                        <div className="relative">`);
p(`                          <Lock className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />`);
p(`                          <input type={showPw[field] ? 'text' : 'password'} value={passwordForm[field]} required`);
p(`                            onChange={e => setPasswordForm(p => ({ ...p, [field]: e.target.value }))}`);
p(`                            className="w-full pl-11 pr-11 py-3 rounded-xl border border-emerald-100 bg-white/50 focus:outline-none focus:ring-2 focus:ring-emerald-500/50 focus:border-emerald-500" />`);
p(`                          <button type="button" onClick={() => setShowPw(p => ({ ...p, [field]: !p[field] }))}`);
p(`                            className="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600">`);
p(`                            {showPw[field] ? <EyeOff className="w-5 h-5" /> : <Eye className="w-5 h-5" />}`);
p(`                          </button>`);
p(`                        </div>`);
p(`                      </div>`);
p(`                    ))}`);
p(`                  </div>`);
p(`                  <button type="submit" disabled={loading}`);
p(`                    className="mt-6 px-6 py-3 bg-gradient-to-r from-emerald-500 to-teal-600 text-white rounded-xl font-medium hover:shadow-lg hover:shadow-emerald-500/30 transition-all disabled:opacity-50 flex items-center gap-2">`);
p(`                    {loading && <Loader2 className="w-4 h-4 animate-spin" />}Update Password`);
p(`                  </button>`);
p(`                </div>`);
p(`              </form>`);
p(`              <div className="backdrop-blur-lg bg-white/60 border border-white/50 rounded-2xl p-6 shadow-xl">`);
p(`                <div className="flex items-center justify-between">`);
p(`                  <div><h3 className="font-bold text-gray-800">Two-Factor Authentication</h3><p className="text-sm text-gray-600 mt-1">Add an extra layer of security</p></div>`);
p(`                  <div className="flex items-center gap-3">`);
p(`                    <span className={\`px-3 py-1 rounded-full text-sm font-medium \${twoFAEnabled ? 'bg-emerald-100 text-emerald-700' : 'bg-gray-100 text-gray-600'}\`}>`);
p(`                      {twoFAEnabled ? 'Enabled' : 'Disabled'}`);
p(`                    </span>`);
p(`                    <Toggle on={twoFAEnabled} onToggle={handle2FAToggle} />`);
p(`                  </div>`);
p(`                </div>`);
p(`              </div>`);
p(`              <div className="backdrop-blur-lg bg-white/60 border border-white/50 rounded-2xl p-6 shadow-xl">`);
p(`                <h3 className="font-bold text-gray-800 mb-4">Connected Devices</h3>`);
p(`                <div className="space-y-3">`);
p(`                  {[`);
p(`                    { device: 'This Browser', location: 'Current session', icon: Monitor, current: true },`);
p(`                    { device: 'Mobile App', location: 'Last seen 2 days ago', icon: Smartphone, current: false },`);
p(`                  ].map((item, i) => (`);
p(`                    <div key={i} className="flex items-center justify-between p-4 rounded-xl bg-white/50 border border-emerald-100">`);
p(`                      <div className="flex items-center gap-3">`);
p(`                        <div className="w-10 h-10 rounded-xl bg-emerald-100 flex items-center justify-center"><item.icon className="w-5 h-5 text-emerald-600" /></div>`);
p(`                        <div><p className="font-medium text-gray-800">{item.device}</p><p className="text-sm text-gray-600">{item.location}</p></div>`);
p(`                        {item.current && <span className="px-2 py-1 bg-emerald-100 text-emerald-700 rounded-full text-xs font-medium">Current</span>}`);
p(`                      </div>`);
p(`                      {!item.current && (`);
p(`                        <button type="button" onClick={() => showMessage('success', 'Device removed')} className="text-red-500 hover:text-red-700 text-sm font-medium">Remove</button>`);
p(`                      )}`);
p(`                    </div>`);
p(`                  ))}`);
p(`                </div>`);
p(`              </div>`);
p(`              <div className="backdrop-blur-lg bg-red-50/60 border border-red-200/50 rounded-2xl p-6 shadow-xl">`);
p(`                <h3 className="font-bold text-red-800 mb-4 flex items-center gap-2"><AlertTriangle className="w-5 h-5" />Danger Zone</h3>`);
p(`                <div className="space-y-3">`);
p(`                  <button type="button" onClick={handleLogout} className="w-full flex items-center justify-between p-4 rounded-xl bg-white/50 border border-red-200 hover:bg-red-50 transition-colors group">`);
p(`                    <div className="flex items-center gap-3"><LogOut className="w-5 h-5 text-red-600" /><div className="text-left"><p className="font-medium text-gray-800">Sign Out</p><p className="text-sm text-gray-600">Sign out of your account</p></div></div>`);
p(`                    <ChevronRight className="w-5 h-5 text-gray-400 group-hover:text-red-600" />`);
p(`                  </button>`);
p(`                  <button type="button" onClick={handleDeleteAccount} className="w-full flex items-center justify-between p-4 rounded-xl bg-white/50 border border-red-200 hover:bg-red-50 transition-colors group">`);
p(`                    <div className="flex items-center gap-3"><Trash2 className="w-5 h-5 text-red-600" /><div className="text-left"><p className="font-medium text-gray-800">Delete Account</p><p className="text-sm text-gray-600">Permanently delete your account and all data</p></div></div>`);
p(`                    <ChevronRight className="w-5 h-5 text-gray-400 group-hover:text-red-600" />`);
p(`                  </button>`);
p(`                </div>`);
p(`              </div>`);
p(`            </div>`);
p(`          )}`);
p(``);
p(`          {/* FARM SETTINGS */}`);
p(`          {activeTab === 'farm' && (`);
p(`            <div className="space-y-6">`);
p(`              <div><h2 className="text-2xl font-bold text-gray-800 mb-1">Farm Settings</h2><p className="text-gray-600">Configure your default farm preferences</p></div>`);
p(`              <div className="backdrop-blur-lg bg-white/60 border border-white/50 rounded-2xl p-6 shadow-xl">`);
p(`                <h3 className="font-bold text-gray-800 mb-4">Farm Preferences</h3>`);
p(`                <div className="space-y-4">`);
p(`                  <div>`);
p(`                    <label className="block text-sm font-medium text-gray-700 mb-2">Default Farm</label>`);
p(`                    <select value={farmPrefs.default_farm} onChange={e => setFarmPrefs(p => ({ ...p, default_farm: e.target.value }))} className="w-full px-4 py-3 rounded-xl border border-emerald-100 bg-white/50 focus:outline-none focus:ring-2 focus:ring-emerald-500/50">`);
p(`                      <option value="">— Select a farm —</option>`);
p(`                      {farms.map(f => <option key={f.farm_id} value={f.farm_id}>{f.name}</option>)}`);
p(`                      {farms.length === 0 && <option disabled>No farms yet — add one in Farm Management</option>}`);
p(`                    </select>`);
p(`                  </div>`);
p(`                  <div>`);
p(`                    <label className="block text-sm font-medium text-gray-700 mb-2">Primary Crop Type</label>`);
p(`                    <select value={farmPrefs.primary_crop} onChange={e => setFarmPrefs(p => ({ ...p, primary_crop: e.target.value }))} className="w-full px-4 py-3 rounded-xl border border-emerald-100 bg-white/50 focus:outline-none focus:ring-2 focus:ring-emerald-500/50">`);
p(`                      {['wheat','rice','corn','soybeans','cotton','barley','sorghum','oats'].map(c => <option key={c} value={c}>{c.charAt(0).toUpperCase() + c.slice(1)}</option>)}`);
p(`                    </select>`);
p(`                  </div>`);
p(`                  <div>`);
p(`                    <label className="block text-sm font-medium text-gray-700 mb-2">Farming Type</label>`);
p(`                    <select value={farmPrefs.farming_type} onChange={e => setFarmPrefs(p => ({ ...p, farming_type: e.target.value }))} className="w-full px-4 py-3 rounded-xl border border-emerald-100 bg-white/50 focus:outline-none focus:ring-2 focus:ring-emerald-500/50">`);
p(`                      <option value="organic">Organic</option><option value="conventional">Conventional</option><option value="mixed">Mixed</option><option value="regenerative">Regenerative</option>`);
p(`                    </select>`);
p(`                  </div>`);
p(`                </div>`);
p(`                <button type="button" onClick={handleFarmPrefsSave} className="mt-6 px-6 py-3 bg-gradient-to-r from-emerald-500 to-teal-600 text-white rounded-xl font-medium hover:shadow-lg hover:shadow-emerald-500/30 transition-all">Save Farm Settings</button>`);
p(`              </div>`);
p(`              {farms.length > 0 && (`);
p(`                <div className="backdrop-blur-lg bg-white/60 border border-white/50 rounded-2xl p-6 shadow-xl">`);
p(`                  <h3 className="font-bold text-gray-800 mb-4">Your Farms ({farms.length})</h3>`);
p(`                  <div className="space-y-3">`);
p(`                    {farms.map(f => (`);
p(`                      <div key={f.farm_id} className="flex items-center justify-between p-4 rounded-xl bg-white/50 border border-emerald-100">`);
p(`                        <div>`);
p(`                          <p className="font-medium text-gray-800">{f.name}</p>`);
p(`                          <p className="text-sm text-gray-600">{f.area_hectares} ha{f.current_crop ? \` · \${f.current_crop}\` : ''}{f.region ? \` · \${f.region}\` : ''}</p>`);
p(`                        </div>`);
p(`                        {farmPrefs.default_farm === f.farm_id && <span className="px-2 py-1 bg-emerald-100 text-emerald-700 rounded-full text-xs font-medium">Default</span>}`);
p(`                      </div>`);
p(`                    ))}`);
p(`                  </div>`);
p(`                </div>`);
p(`              )}`);
p(`            </div>`);
p(`          )}`);
p(``);
p(`        </div>`);
p(`      </div>`);
p(`    </div>`);
p(`  );`);
p(`}`);

fs.writeFileSync(file, lines.join('\n'), 'utf8');
console.log('Done! Lines:', lines.length);
