"""Add feedback table

Revision ID: 726b7bccd485
Revises: 1710475a7cce
Create Date: 2026-05-17 00:49:34.749176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '726b7bccd485'
down_revision: Union[str, None] = '1710475a7cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Enum('correct', 'partially_correct', 'incorrect', name='feedback_rating_enum'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('actual_outcome', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.prediction_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id'),
    sa.UniqueConstraint('prediction_id', 'user_id', name='uq_feedback_prediction_user')
    )
    op.create_index('idx_feedback_user', 'feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_feedback_user', table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
